name: å•å…ƒæµ‹è¯•

on:
  workflow_dispatch:
    inputs:
      target_platforms:
        description: "è¾“å…¥ç›®æ ‡å¹³å°ï¼ˆå¯é€‰ï¼šwindows-latest/ubuntu-latest/macos-latestï¼‰"
        required: false
        type: string
        default: '["windows-latest", "ubuntu-latest", "macos-latest"]'
      node_versions:
        description: "è¾“å…¥è¿è¡Œç¯å¢ƒï¼ˆå‚è€ƒï¼šhttps://nodejs.org/download/release/ï¼‰"
        required: false
        type: string
        default: '["20", "22", "24"]'
  workflow_call:
    inputs:
      target_platforms:
        description: "è¾“å…¥ç›®æ ‡å¹³å°ï¼ˆå¯é€‰ï¼šwindows-latest/ubuntu-latest/macos-latestï¼‰"
        required: false
        type: string
        default: '["windows-latest", "ubuntu-latest", "macos-latest"]'
      node_versions:
        description: "è¾“å…¥è¿è¡Œç¯å¢ƒï¼ˆå‚è€ƒï¼šhttps://nodejs.org/download/release/ï¼‰"
        required: false
        type: string
        default: '["20", "22", "24"]'

permissions:
  checks: write
  contents: read
  actions: read
  security-events: write

jobs:
  test:
    name: æµ‹è¯• node${{ matrix.node }}.${{ matrix.os }} ç¯å¢ƒ
    runs-on: ${{ matrix.os }}
    env:
      TZ: "Asia/Shanghai"
    strategy:
      fail-fast: false
      matrix:
        node: ${{ fromJson(github.event.inputs.node_versions || inputs.node_versions) }}
        os: ${{ fromJson(github.event.inputs.target_platforms || inputs.target_platforms) }}

    steps:
      - name: æ£€å‡ºé¡¹ç›®ä»“åº“
        uses: actions/checkout@v5

      - name: è®¾ç½®æµ‹è¯•ç¯å¢ƒ
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          registry-url: "https://registry.npmjs.org"

      - name: å®‰è£…ä¾èµ–å·¥å…·
        if: matrix.os == 'windows-latest'
        run: |
          choco install 7zip -y
          choco install unzip -y
          choco install zip -yy

      - name: è¿è¡Œå•å…ƒæµ‹è¯•
        id: test_result
        shell: bash
        run: |
          echo "ğŸ” å¼€å§‹æµ‹è¯•..."
          npm install
          mkdir -p tests/reports
          if ! npm test > tests/reports/output.log 2>&1; then
            echo "âŒ æµ‹è¯•å¤±è´¥"
            cat tests/reports/output.log
            exit 1
          fi
          cat tests/reports/output.log
          echo "âœ… æµ‹è¯•é€šè¿‡"

      - name: ä¸Šä¼ æµ‹è¯•æŠ¥å‘Š
        uses: actions/upload-artifact@v5
        if: always()
        with:
          name: test#${{ github.run_number }}.node${{ matrix.node }}.${{ matrix.os }}.reports
          path: tests/reports
          retention-days: 14